using System;

/// <summary>Provides access to SDK functions.</summary>
public interface ISdkService : IDisposable
{
    /// <summary>Gets the UUID assigned to device by ArborXR.</summary>
    /// <returns>UUID is provided as a string.</returns>
    string GetDeviceId();

    /// <summary>Gets the serial number assigned to device by OEM.</summary>
    /// <returns>Serial number is provided as a string.</returns>
    string GetDeviceSerial();

    /// <summary>Gets the title given to device by admin through the ArborXR Web Portal.</summary>
    string GetDeviceTitle();

    /// <summary>Gets the tags added to device by admin through the ArborXR Web Portal.</summary>
    /// <returns>
    ///   Tags are represented as a string array. Array will be empty if no tags are assigned to device.
    /// </returns>
    string[] GetDeviceTags();

    /// <summary>
    ///   Gets the UUID of the organization where the device is assigned. Organizations are created in the
    ///   ArborXR Web Portal.
    /// </summary>
    /// <returns>UUID is provided as a string.</returns>
    string GetOrgId();

    /// <summary>Gets the name assigned to organization by admin through the ArborXR Web Portal.</summary>
    string GetOrgTitle();

    /// <summary>Gets the identifier generated by ArborXR when admin assigns title to organization.</summary>
    string GetOrgSlug();

    /// <summary>Gets the physical MAC address assigned to device by OEM.</summary>
    /// <returns>MAC address is provided as a string.</returns>
    string GetMacAddressFixed();

    /// <summary>Gets the randomized MAC address for the current WiFi connection.</summary>
    /// <returns>MAC address is provided as a string.</returns>
    string GetMacAddressRandom();

    /// <summary>Gets whether the device is SSO authenticated.</summary>
    /// <returns>Whether the device is SSO authenticated.</returns>
    bool GetIsAuthenticated();

    /// <summary>Gets SSO access token.</summary>
    /// <returns>SSO access token.</returns>
    string GetAccessToken();

    /// <summary>Gets SSO refresh token.</summary>
    /// <returns>SSO refresh token.</returns>
    string GetRefreshToken();

    /// <summary>Gets SSO token remaining lifetime.</summary>
    /// <returns>The remaining lifetime of the access token in seconds.</returns>
    DateTime? GetExpiresDateUtc();

    /// <summary>Gets whether the XRDM client is initialized.</summary>
    /// <returns>Whether the XRDM client is initialized.</returns>
    bool GetIsInitialized();

    // <summary>Gets the device fingerprint.</summary>
    /// <returns>The device fingerprint.</returns>
    string GetFingerprint();
}